models/Post.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Html;

/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property string $title
 * @property string $content
 * @property string $tags
 * @property int $status
 * @property int $create_time
 * @property int $update_time
 * @property int $author_id
 *
 * @property Comment[] $comments
 * @property User $author
 */
class Post extends \yii\db\ActiveRecord
{
    const STATUS_DRAFT=1;
    const STATUS_PUBLISHED=2;
    const STATUS_ARCHIVED=3;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'content', 'status'], 'required'],
            [['title'], 'string', 'max' => 128],
            [['status'], 'in', 'range' => [1,2,3]],
            [['tags'], 'match', 'pattern'=>'/^[\w\s,]+$/',
                'message'=>'В тегах можно использовать только буквы.'],
            [['tags'], 'normalizeTags'],
            [['title', 'status'], 'safe', 'on' => 'search'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'content' => 'Content',
            'tags' => 'Tags',
            'status' => 'Status',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
            'author_id' => 'Author ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(Comment::className(), ['post_id' => 'id'])
                   ->onCondition(['status' => Comment::STATUS_APPROVED]);
    }

    public function getCommentsCount()
    {
        return $this->getComments()->count();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'author_id']);
    }

    public function normalizeTags($attribute,$params)
    {
            $this->tags=Tag::array2string(array_unique(Tag::string2array($this->tags)));
    }
    
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->create_time = $this->update_time = time();
                $this->author_id = Yii::$app->user->id;
            } else {
                $this->update_time=time();
            }
            return true;
        } else {
            return false;
        }
    }
    
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        Tag::updateFrequency($this->_oldTags, $this->tags);
    }

    private $_oldTags;

    public function afterFind()
    {
        parent::afterFind();
        $this->_oldTags = $this->tags;
    }

    public function getTagLinks()
    {
        $links = array();
        foreach (Tag::string2array($this->tags) as $tag) {
            $links[] = Html::a($tag, ['/post?tag='.$tag]);
        }
        return $links;
    }

    public function addComment($comment)
    {
        $comment->status = Comment::STATUS_PENDING;
        $comment->post_id = $this->id;
        return $comment->save();
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Post;
use app\models\PostSearch;
use app\models\Comment;
use app\models\User;
use app\models\LoginForm;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\HttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'actions' => ['index','view'],
                        'allow' => true,
                        'roles' => ['?']
                    ],
                    [
                        'actions' => ['index','view', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@']
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */

    public function actionIndex()
    {   
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['status' => Post::STATUS_PUBLISHED]);
        $tag = Yii::$app->request->get('tag');
        if (isset($tag)) {
            $dataProvider->query->andWhere(['like', 'tags', $tag]);
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $post = $this->loadModel($id);
        if ($comment = $this->newComment($post)) {
            Yii::$app->session->setFlash('commentSubmitted', 
                'Thank you for your comment. Your comment will be posted once it is approved.');
            return $this->redirect(['view', 'id' => $post->id]);
        } else {
            $comment = new Comment();
        }

        return $this->render('view', [
            'model' => $post,
            'comment' => $comment,
        ]);
    }

    public function loadModel($id)
    {
        if (Yii::$app->user->isGuest) {
            $post = Post::find()
                ->where(['status' => Post::STATUS_PUBLISHED])
                ->orWhere(['status' => Post::STATUS_ARCHIVED])
                ->andWhere(['id' => $id])
                ->one();
        } else {
            $post = Post::findOne($id);
        }
        if ($post === null) {
            throw new HttpException(404, 'The requested Item could not be found.');
        }
        return $post;
    }

    public function newComment($post)
    {
        $comment = new Comment;
        
        if ($comment->load(Yii::$app->request->post()) && $comment->validate()) {
            if ($post->addComment($comment)) {
                return $comment;
            }
        }
        return false;
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Post();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->goHome();
    }
    
    public function actionAdmin()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('admin', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goHome();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout($id)
    {
        $user = User::findOne($id);
        Yii::$app->user->logout($user);
        return $this->goHome();
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/post/_comments.php
<?php

use yii\helpers\Html;

?>
<?php foreach($comments as $comment): ?>
<div class="comment" id="c<?php echo $comment->id; ?>">

    <?= Html::a('#' . $comment->id, ['view?id='.$model->id.'#c'.$comment->id]); ?>

    <div class="author">
        <?php echo $comment->author; ?> says:
    </div>

    <div class="time">
        <?php echo date('F j, Y \a\t h:i a',$comment->create_time); ?>
    </div>

    <div class="content">
        <?= Html::encode($comment->content) ?>
    </div>
    <br>
</div><!-- comment -->
<?php endforeach; ?>

views/post/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Lookup;

/* @var $this yii\web\View */
/* @var $model app\models\Post */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'tags')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'status')->dropDownList(Lookup::items('PostStatus')) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'content') ?>

    <?= $form->field($model, 'tags') ?>

    <?= $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'create_time') ?>

    <?php // echo $form->field($model, 'update_time') ?>

    <?php // echo $form->field($model, 'author_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/_view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="row">

    <div class="blog-post">
        <h2 class="blog-post-title"><a href="<?= Url::to(['post/view', 'id' => $model->id]) ?>"><?= $model->title ?></a></h2>
    </div>    
    <p class="blog-post-meta"><?= Html::encode('posted by ' . $model->author->username . ' on ' . date('F j, Y',$model->create_time)) ?></p>
    <p><?= Html::encode($model->content) ?></p>	
    <?= "Tags: ".implode(', ', $model->tagLinks); ?>

</div>

views/post/admin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Admin';
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-index">

<div class="container">

    <div class="blog-header">
        <h1 class="blog-title">Управление записями</h1>
    </div>
    
    <br>

    <div class="col-sm-8 blog-main">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'summary' => false,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'title',
            'content:ntext',
            'tags:ntext',
            'status',
            //'create_time:datetime',
            //'update_time:datetime',
            //'author_id',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    </div>
    
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    	<?= $this->render('sidebar.php'); ?>
    </div>

</div>
</div>

views/post/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = 'Create Post';
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-create">

<div class="container">

    <div class="blog-header">
        <h1 class="blog-title">Создать новую запись</h1>
    </div>
    
    <br>

    <div class="col-sm-8 blog-main">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
    </div>
   
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    	<?= $this->render('sidebar.php'); ?>
    </div>

</div>
</div>

views/post/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Blog';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="container">

    <div class="col-sm-8 blog-main">
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_view',
	'summary' => false,
    ]); ?>
    </div>

    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    	<?= $this->render('sidebar.php'); ?>
    </div>
</div>
</div>

views/post/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/post/sidebar.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Nav;
use app\models\Tag;
use app\models\Comment;
use app\models\Post;

?>
<div class="sidebar-module">
    
    <?php if (!Yii::$app->user->isGuest): ?>
    <div class="panel panel-default">
    <?= Nav::widget([
        'options' => ['class' => 'nav'],
        'items' => [
            ['label' => 'Одобрить комментарий (' . count(Comment::find()->where(['status' => Comment::STATUS_PENDING])->all()) . ')', 'url' => ['/comment']],
            ['label' => 'Создать новую запись', 'url' => ['/post/create']],
            ['label' => 'Управление записями', 'url' => ['/post/admin']],
        ],
    ]); ?>
    </div>
    <?php endif; ?>
     
    <br>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Теги</h3>
        </div>
        <div class="panel-body">
            <?php $tags=Tag::findTagWeights(20); ?>    
            <?php foreach ($tags as $tag=>$weight): ?>
            <?php 
                $link = Html::a(Html::encode($tag), ['post/index', 'tag' => $tag]); 
                echo Html::tag('span', $link, ['class' => 'tag', 'style' => 'font-size:'.$weight.'pt', 'margin' => 'auto']);
            ?>
            <?php endforeach;?>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Комментарии</h3>
        </div>
    <?php $comments = Comment::findRecentComments(); ?>
    <ul class="list-unstyled">
    <?php foreach ($comments as $comment): ?>
        <p><li style="margin-left: 16px"><?= $comment->author . ' on ' ?>
        <?= Html::a($comment->post->title, ['/post/view', 'id' => $comment->post->id, '#' => 'c'.$comment->id]); ?></li></p>
    <?php endforeach; ?>
    </ul>
    </div>

</div>

views/post/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = 'Update Post: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="post-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="container">

    <div class="blog-header">
        <h1 class="blog-title"><?= Html::encode($this->title) ?></h1>
    </div>

    <div class="col-sm-8 blog-main">
        <?= $this->render('_view', ['model' => $model]) ?>
    </div>
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    	<?= $this->render('sidebar.php'); ?>
    </div>
</div>
<div class="col-sm-8 blog-main">

        <?php if (Yii::$app->session->hasFlash('commentSubmitted')): ?>
        <div class="alert alert-success alert dismissble" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo Yii::$app->session->getFlash('commentSubmitted'); ?>
        </div>
        <?php endif; ?>
    
        <?php if ($model->commentsCount >= 1): ?>
    
        <h3>
            <?php echo $model->commentsCount . ' comment(s)'; ?>
        </h3>
   
        <?= $this->render('_comments', [
            'model' => $model,
            'comments' => $model->comments
        ]) ?>
        <?php endif; ?>
            
        <h3>Оставить комментарий</h3>

        <?= $this->render('/comment/_form', ['model' => $comment]); ?>
    
</div>
        